version: "3.9"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=lol
      - MYSQL_DATABASE=demo
    ports:
      - 3306:3306

  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/demo
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=lol
    volumes:
      - db-data:/var/lib/mysql/data
    depends_on:
      - db

volumes:
  db-data: 

