spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/demo}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:lol}
pw.pepper: 3kFlh3C4Yjyktw320AV6

---
spring:
  datasource:
    username: test
    password: test
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

  config:
    activate:
      on-profile: test
